import React, {useEffect,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {Clock, MapPin, ShieldCheck, Languages, LogOut, User, Gavel, Eye, FileText, Bell, TimerReset, Trophy} from 'lucide-react';
import './styles.css';

const DEMO_USERS = Array.from({length: 10}, (_, i) => ({username:`user${i+1}`, password:`pass${i+1}`}));
const money=n=>'₾'+Math.round(n||0).toLocaleString('en-US');
const fmtTime=ms=>{ if(ms<=0)return 'Ended'; const m=Math.floor(ms/60000),h=Math.floor(m/60),mm=m%60,s=Math.floor((ms%60000)/1000); return h?`${h}h ${mm}m`:`${mm}m ${s}s`; };
async function api(path, opts={}){
 const user=JSON.parse(sessionStorage.gtAuctionUser||'null');
 const res=await fetch(path,{...opts,headers:{'Content-Type':'application/json',...(user?.username?{'x-demo-user':user.username}:{}),...(opts.headers||{})}});
 const data=await res.json().catch(()=>({}));
 if(!res.ok) throw new Error(data.error||'Request failed');
 return data;
}
function VehicleArt({shape,accent}){return <div className="art" style={{'--accent':accent}}><div className={'machine '+shape}><span className="cab"/><span className="body"/><span className="arm"/><span className="bucket"/><span className="drum"/><i/><b/></div><div className="ground"/></div>}
function App(){
 const [state,setState]=useState(null),[user,setUser]=useState(()=>JSON.parse(sessionStorage.gtAuctionUser||'null')),[selected,setSelected]=useState(null),[tick,setTick]=useState(Date.now()),[toast,setToast]=useState('');
 async function refresh(){try{const s=await api('/api/state'); setState(s); if(!selected&&s.lots?.[0]) setSelected(s.lots[0].id);}catch(e){setToast(e.message)}}
 useEffect(()=>{refresh(); const t=setInterval(()=>{setTick(Date.now()); refresh()},1200); return()=>clearInterval(t)},[]);
 const lot=state?.lots?.find(l=>l.id===selected)||state?.lots?.[0];
 async function doLogin(username,password){try{const {user:u}=await api('/api/login',{method:'POST',body:JSON.stringify({username,password})}); sessionStorage.gtAuctionUser=JSON.stringify(u); setUser(u); setToast(`Logged in as ${u.username} — verified bidder`)}catch(e){setToast(e.message)}}
 function logout(){sessionStorage.removeItem('gtAuctionUser'); setUser(null); setToast('Logged out')}
 async function action(path, body){try{const r=await api(path,{method:'POST',body:JSON.stringify(body)}); setState(r.state); setToast(r.message||'Done')}catch(e){setToast(e.message)}}
 if(!state||!lot) return <div className="loading">Loading GT Auction demo…</div>;
 return <><header><div className="brand"><div className="logo">GT</div><div><b>Auction</b><span>Construction equipment demo</span></div></div><nav><a>Auctions</a><a>How it works</a><a>Terms</a><div className="langs"><Languages size={14}/> KA / EN / RU</div>{user?<button onClick={logout} className="ghost"><LogOut size={16}/>{user.username}</button>:<button onClick={()=>document.getElementById('loginPanel')?.scrollIntoView({behavior:'smooth'})}>Login</button>}</nav></header><main><section className="hero"><div className="heroText"><div className="eyebrow"><ShieldCheck size={16}/> verified demo bidders only</div><h1>GT Group construction vehicle auctions</h1><p>A quick presentation MVP: live shared bidding from phones, proxy bids, Buy Now requests, anonymous history, and manager-approved auction flow.</p><div className="heroBtns"><button onClick={()=>document.getElementById('lots').scrollIntoView()}>View active auctions</button><button className="secondary" onClick={()=>action('/api/reset',{})}>Reset demo</button></div><div className="stats"><span><b>10</b> demo users</span><span><b>5</b> active lots</span><span><b>Live</b> shared bids</span></div></div><div className="heroCard"><VehicleArt shape="excavator" accent="#56B461"/><div className="live"><span/> Live auction demo</div></div></section><section id="loginPanel" className="loginCard"><LoginForm login={doLogin}/><DemoUsers/></section><section id="lots" className="grid"><div><div className="sectionTitle"><h2>Active construction lots</h2><p>SHACMAN and CASE inventory for the meeting.</p></div><div className="cards">{state.lots.map(l=><LotCard key={l.id} lot={l} active={l.id===selected} onClick={()=>setSelected(l.id)} tick={tick}/>)}</div></div><LotDetail lot={lot} tick={tick} user={user} onBid={(amount)=>action('/api/bid',{lotId:lot.id,amount})} onProxy={(max)=>action('/api/proxy',{lotId:lot.id,max})} onBuy={()=>action('/api/buy-now',{lotId:lot.id})}/></section></main><footer><div className="rings"/><b>GT Auction</b><span>Presentation demo — shared backend, still not production software</span></footer>{toast&&<div className="toast" onAnimationEnd={()=>setToast('')}>{toast}</div>}</>}
function LoginForm({login}){const [u,setU]=useState('user1'),[p,setP]=useState('pass1'); return <form onSubmit={e=>{e.preventDefault();login(u,p)}}><h3>Demo bidder login</h3><div className="row"><input value={u} onChange={e=>setU(e.target.value)} placeholder="username" autoCapitalize="none"/><input value={p} onChange={e=>setP(e.target.value)} placeholder="password" autoCapitalize="none"/><button>Login</button></div></form>}
function DemoUsers(){return <div className="demoUsers">{DEMO_USERS.map(u=><span key={u.username}><User size={13}/>{u.username}/{u.password}</span>)}</div>}
function LotCard({lot,active,onClick,tick}){return <button className={'lotCard '+(active?'active':'')} onClick={onClick}><VehicleArt shape={lot.shape} accent={lot.accent}/><div className="lotMeta"><span className="badge">{lot.brand}</span>{lot.buyRequested&&<span className="buyBadge">Buy Now requested</span>}<h3>{lot.model}</h3><p>{lot.year} • {lot.type} • {lot.hours}</p><div className="price"><span>Current bid</span><b>{money(lot.current)}</b></div><div className="mini"><span><Clock size={14}/>{fmtTime(lot.endAt-tick)}</span><span><MapPin size={14}/>{lot.location}</span></div></div></button>}
function LotDetail({lot,tick,user,onBid,onProxy,onBuy}){const [amount,setAmount]=useState(lot.current+lot.increment),[proxy,setProxy]=useState(lot.current+lot.increment*4); useEffect(()=>{setAmount(lot.current+lot.increment); setProxy(lot.current+lot.increment*4)},[lot.id,lot.current]); return <aside className="detail"><div className="detailTop"><VehicleArt shape={lot.shape} accent={lot.accent}/><div><span className="badge big">{lot.brand}</span><h2>{lot.model}</h2><p>{lot.type} • {lot.year} • {lot.hours}</p></div></div><div className="count"><TimerReset/> <b>{fmtTime(lot.endAt-tick)}</b><span>remaining</span></div><div className="numbers"><div><span>Current bid</span><b>{money(lot.current)}</b></div><div><span>Increment</span><b>{money(lot.increment)}</b></div><div><span>Buy Now</span><b>{money(lot.buyNow)}</b></div></div>{lot.suspicious&&<div className="warn"><Bell size={16}/> Manager alert: suspicious jump flagged</div>}<div className="bidBox"><label>Place next bid</label><div className="row"><input type="number" value={amount} onChange={e=>setAmount(+e.target.value)}/><button onClick={()=>onBid(amount)}><Gavel size={16}/> Place bid</button></div><label>Proxy bid / Bid up to</label><div className="row"><input type="number" value={proxy} onChange={e=>setProxy(+e.target.value)}/><button className="secondary" onClick={()=>onProxy(proxy)}>Save proxy</button></div><button className="buy" onClick={onBuy}>Buy Now request</button><p className="note">{user?`${user.username} is verified. Bid ceiling: ${money(user.limit)}.`:'Login with a demo verified user to bid.'}</p></div><div className="docs"><span><FileText size={14}/> Inspection PDF</span><span><Eye size={14}/> Public anonymous history</span></div><h3>Bid history</h3><div className="history">{lot.bids.map((b,i)=><div key={i}><span>{b.type==='proxy_auto'?'Proxy bidder':'Anonymous bidder'} #{String(Math.abs(hash(b.user))).slice(0,3)}</span><b>{money(b.amount)}</b></div>)}</div><div className="winner"><Trophy size={16}/> Winner will be pending GT manager approval.</div></aside>}
function hash(s){return [...String(s)].reduce((a,c)=>((a<<5)-a+c.charCodeAt(0))|0,0)}
createRoot(document.getElementById('root')).render(<App/>);
