import React, { useEffect, useMemo, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { Bell, CheckCircle2, ChevronRight, Clock3, FileText, Filter, Gavel, Languages, LockKeyhole, LogOut, MapPin, Pencil, Plus, RotateCcw, ShieldCheck, Trash2, User, Wrench, X } from 'lucide-react';
import './styles.css';

const DEMO_USERS = Array.from({ length: 5 }, (_, i) => ({ username: `user${i + 1}`, password: `pass${i + 1}` }));
const images = {
  'shacman-x3000': '/lots/shacman-x3000.png',
  'shacman-f3000-dump': '/lots/shacman-f3000-dump.png',
  'shacman-l3000-mixer': '/lots/shacman-l3000-mixer.png',
  'case-580st': '/lots/case-580st.png',
  'case-cx220c': '/lots/case-cx220c.png',
};
const imageFor = lot => images[lot?.id] || images[lot?.imageKey] || images['shacman-x3000'];
const money = n => '₾' + Math.round(n || 0).toLocaleString('en-US');
const fmtTime = ms => { if (ms <= 0) return 'Ended'; const m = Math.floor(ms / 60000), h = Math.floor(m / 60), mm = m % 60, s = Math.floor((ms % 60000) / 1000); return h ? `${h}h ${mm}m` : `${mm}m ${s}s`; };
const lotStatuses = ['draft', 'scheduled', 'live', 'ended', 'pending_approval', 'approved', 'cancelled'];
const statusLabel = s => String(s || 'live').replace('_', ' ');
const toLocalInput = ms => new Date(ms - new Date().getTimezoneOffset() * 60000).toISOString().slice(0, 16);
async function api(path, opts = {}) {
  const user = JSON.parse(sessionStorage.gtAuctionUser || 'null');
  const admin = JSON.parse(sessionStorage.gtAuctionAdmin || 'null');
  const res = await fetch(path, { ...opts, headers: { 'Content-Type': 'application/json', ...(user?.token ? { 'x-user-token': user.token } : user?.username ? { 'x-demo-user': user.username } : {}), ...(admin?.token ? { 'x-admin-token': admin.token } : {}), ...(opts.headers || {}) } });
  const data = await res.json().catch(() => ({}));
  if (!res.ok) throw new Error(data.error || 'Request failed');
  return data;
}

function App() {
  const [state, setState] = useState(null), [user, setUser] = useState(() => JSON.parse(sessionStorage.gtAuctionUser || 'null'));
  const [admin, setAdmin] = useState(() => JSON.parse(sessionStorage.gtAuctionAdmin || 'null'));
  const [tick, setTick] = useState(Date.now()), [toast, setToast] = useState(''), [filter, setFilter] = useState('All'), [selectedLot, setSelectedLot] = useState(null);
  async function refresh() { try { setState(await api('/api/state')); } catch (e) { setToast(e.message); } }
  useEffect(() => { refresh(); const t = setInterval(() => { setTick(Date.now()); refresh(); }, 1800); return () => clearInterval(t); }, []);
  async function login(username, password) { try { const { user: u } = await api('/api/login', { method: 'POST', body: JSON.stringify({ username, password }) }); sessionStorage.gtAuctionUser = JSON.stringify(u); setUser(u); setToast(`Logged in as ${u.username}`); } catch (e) { setToast(e.message); } }
  async function adminLogin(username, password) { try { const { admin: a } = await api('/api/admin/login', { method: 'POST', body: JSON.stringify({ username, password }) }); sessionStorage.gtAuctionAdmin = JSON.stringify(a); setAdmin(a); setToast('Admin panel unlocked'); } catch (e) { setToast(e.message); } }
  function logout() { sessionStorage.removeItem('gtAuctionUser'); setUser(null); setToast('Logged out'); }
  function adminLogout() { sessionStorage.removeItem('gtAuctionAdmin'); setAdmin(null); setToast('Admin locked'); }
  async function action(path, body, method = 'POST') { try { const r = await api(path, { method, body: method === 'DELETE' ? undefined : JSON.stringify(body) }); setState(r.state); setToast(r.message || 'Done'); return true; } catch (e) { setToast(e.message); return false; } }
  const lots = state?.lots || [];
  const filteredLots = useMemo(() => lots.filter(l => filter === 'All' || l.brand === filter || l.type.includes(filter)), [lots, filter]);
  if (!state) return <div className="loading">Loading GT Auction…</div>;
  return <>
    <Header user={user} admin={admin} logout={logout} adminLogout={adminLogout} />
    <main>
      <Hero lot={lots[0]} tick={tick} reset={() => action('/api/reset', {})} openBid={setSelectedLot} />
      <section className="trustStrip"><span><ShieldCheck size={18}/> Verified lots</span><span><FileText size={18}/> Inspection-ready records</span><span><LockKeyhole size={18}/> Confirm-before-bid flow</span><span><Bell size={18}/> Manager approval after auction</span></section>
      <section className="auctionShell" id="auctions"><div className="toolbar"><div><span className="kicker"><Filter size={15}/> Active inventory</span><h2>Heavy equipment auctions</h2><p>Initial demo inventory: SHACMAN and CASE. Partner brands can be added later.</p></div><div className="filters">{['All', 'SHACMAN', 'CASE', 'Truck', 'Excavator'].map(f => <button key={f} className={filter === f ? 'chip active' : 'chip'} onClick={() => setFilter(f)}>{f}</button>)}</div></div><div className="lotGrid">{filteredLots.map(lot => <LotCard key={lot.id} lot={lot} tick={tick} openBid={setSelectedLot} />)}</div></section>
      <section className="bottomPanel" id="login"><LoginForm login={login} user={user} /><DemoUsers /></section>
      <AdminPanel admin={admin} login={adminLogin} lots={lots} tick={tick} action={action} />
    </main>
    <footer><b>GT Auction</b><span>Presentation MVP — visual prototype with working demo bidding backend.</span></footer>
    {selectedLot && <BidModal lot={selectedLot} tick={tick} user={user} close={() => setSelectedLot(null)} onBid={(amount) => action('/api/bid', { lotId: selectedLot.id, amount })} onProxy={(max) => action('/api/proxy', { lotId: selectedLot.id, max })} onBuy={() => action('/api/buy-now', { lotId: selectedLot.id })} />}
    {toast && <div className="toast" onAnimationEnd={() => setToast('')}>{toast}</div>}
  </>;
}
function Header({ user, admin, logout, adminLogout }) { return <header><a className="brand" href="#top"><span className="mark">GT</span><span><b>GT Auction</b><small>Heavy equipment marketplace</small></span></a><nav><a href="#auctions">Auctions</a><a href="#admin">Admin</a><span className="language"><Languages size={14}/> KA / EN</span>{admin && <button className="ghost dark" onClick={adminLogout}><Wrench size={15}/>admin</button>}{user ? <button className="ghost dark" onClick={logout}><LogOut size={15}/>{user.username}</button> : <a className="loginLink" href="#login">Login</a>}</nav></header>; }
function Hero({ lot, tick, reset, openBid }) { if (!lot) return null; return <section className="hero" id="top"><div className="heroCopy"><span className="kicker"><ShieldCheck size={16}/> GT Group verified auction lots</span><h1>Heavy Equipment Auctions</h1><p>Bid on selected SHACMAN and CASE construction vehicles with transparent history, confirmed bidder actions, and offline GT manager approval.</p><div className="heroActions"><a className="primary" href="#auctions">View auctions <ChevronRight size={18}/></a><button className="secondary" onClick={reset}><RotateCcw size={16}/> Reset demo</button></div><div className="metrics"><span><b>5</b> demo bidders</span><span><b>Admin</b> editable lots</span><span><b>₾</b> GEL bidding</span></div></div><div className="featureCard"><img src={imageFor(lot)} alt={lot.model}/><div className="featureOverlay"><span className="liveDot">Live lot</span><h3>{lot.brand} {lot.model}</h3><div className="featureStats"><span><small>Current bid</small><b>{money(lot.current)}</b></span><span><small>Ends in</small><b>{fmtTime(lot.endAt - tick)}</b></span></div><button onClick={() => openBid(lot)}>Open bid panel</button></div></div></section>; }
function LotCard({ lot, tick, openBid }) { const ended = lot.endAt - tick <= 0, live = (lot.status || 'live') === 'live'; return <article className="lotCard"><div className="photoWrap"><img src={imageFor(lot)} alt={lot.model}/><span className="brandBadge">{lot.brand}</span><span className="statusBadge">{statusLabel(lot.status)}</span>{lot.buyRequested && <span className="requestBadge">Buy request</span>}</div><div className="lotBody"><div className="lotHead"><div><h3>{lot.model}</h3><p>{lot.type} · {lot.year} · {lot.hours}</p></div><span className={ended ? 'timer ended' : 'timer'}><Clock3 size={14}/>{fmtTime(lot.endAt - tick)}</span></div><div className="specs"><span><MapPin size={14}/>{lot.location}</span><span><CheckCircle2 size={14}/> Verified lot</span><span><FileText size={14}/> Inspection report</span></div><div className="priceRow"><span><small>Current bid</small><b>{money(lot.current)}</b></span><span><small>Increment</small><b>{money(lot.increment)}</b></span></div><button className="bidOpen" disabled={!live} onClick={() => openBid(lot)}>{live ? 'Place bid safely' : 'Bidding closed'} <ChevronRight size={16}/></button></div></article>; }
function BidModal({ lot, tick, user, close, onBid, onProxy, onBuy }) { const [amount, setAmount] = useState(lot.current + lot.increment), [proxy, setProxy] = useState(lot.current + lot.increment * 4); useEffect(() => { setAmount(lot.current + lot.increment); setProxy(lot.current + lot.increment * 4); }, [lot.id, lot.current, lot.increment]); const min = lot.current + lot.increment, live = (lot.status || 'live') === 'live'; async function confirmBid() { if (await onBid(amount)) close(); } return <div className="modalBackdrop" onMouseDown={close}><section className="bidModal" onMouseDown={e => e.stopPropagation()}><button className="modalClose" onClick={close}><X size={18}/></button><div className="modalPhoto"><img src={imageFor(lot)} alt={lot.model}/><span>{lot.brand}</span></div><div className="modalContent"><span className="kicker"><Gavel size={15}/> Confirm bidder action</span><h2>{lot.model}</h2><p>{lot.type} · {lot.year} · {lot.location}</p><div className="modalNumbers"><div><small>Current bid</small><b>{money(lot.current)}</b></div><div><small>Minimum next bid</small><b>{money(min)}</b></div><div><small>Time left</small><b>{fmtTime(lot.endAt - tick)}</b></div></div><div className="confirmBox"><label>Bid amount</label><div className="inputAction"><input type="number" min={min} step={lot.increment} value={amount} onChange={e => setAmount(Number(e.target.value))}/><button onClick={confirmBid} disabled={!user || !live}>BID NOW</button></div><div className="quickBids">{[min, min + lot.increment, min + lot.increment * 2].map(v => <button key={v} onClick={() => setAmount(v)}>{money(v)}</button>)}</div><p className="safety"><LockKeyhole size={14}/> This confirmation window prevents accidental one-click bids from the homepage.</p></div><div className="secondaryActions"><div><label>Proxy bid up to</label><div className="inputAction"><input type="number" value={proxy} onChange={e => setProxy(Number(e.target.value))}/><button className="secondary" onClick={() => onProxy(proxy)} disabled={!user || !live}>Save proxy</button></div></div><button className="buyNow" onClick={onBuy} disabled={!user || !live}>Request Buy Now at {money(lot.buyNow)}</button></div><p className="loginNote">{user ? `${user.username} verified · ceiling ${money(user.limit)}` : 'Login with a demo bidder before confirming a bid.'}</p></div></section></div>; }
function LoginForm({ login, user }) { const [u, setU] = useState('user1'), [p, setP] = useState('pass1'); return <form className="loginCard" onSubmit={e => { e.preventDefault(); login(u, p); }}><span className="kicker"><User size={15}/> Demo access</span><h3>{user ? `Logged in as ${user.username}` : 'Verified bidder login'}</h3><div className="loginInputs"><input value={u} onChange={e => setU(e.target.value)} placeholder="username"/><input value={p} onChange={e => setP(e.target.value)} placeholder="password"/><button>Login</button></div></form>; }
function DemoUsers() { return <div className="demoUsers"><b>Demo users</b>{DEMO_USERS.map(u => <span key={u.username}>{u.username} / {u.password}</span>)}</div>; }

function AdminPanel({ admin, login, lots, tick, action }) {
  const [u, setU] = useState('admin'), [p, setP] = useState('admin'), [editing, setEditing] = useState(null), [hours, setHours] = useState(8);
  if (!admin) return <section className="adminShell" id="admin"><form className="adminLogin" onSubmit={e => { e.preventDefault(); login(u, p); }}><span className="kicker"><Wrench size={15}/> Admin panel</span><h2>Manage demo auctions</h2><p>Login: <b>admin</b> / <b>admin</b></p><div className="loginInputs"><input value={u} onChange={e => setU(e.target.value)} /><input value={p} onChange={e => setP(e.target.value)} /><button>Open admin</button></div></form></section>;
  return <section className="adminShell" id="admin"><div className="adminHead"><div><span className="kicker"><Wrench size={15}/> Admin panel</span><h2>Manage auction lots</h2><p>Add/remove lots, adjust prices, and keep auctions open without touching code.</p></div><div className="adminTools"><input type="number" value={hours} onChange={e => setHours(Number(e.target.value))}/><button onClick={() => action('/api/admin/open-hours', { hours })}>Open all for {hours}h</button><button className="secondary" onClick={() => setEditing(blankLot())}><Plus size={16}/> Add lot</button></div></div><div className="adminList">{lots.map(l => <div className="adminRow" key={l.id}><img src={imageFor(l)} /><div><b>{l.brand} {l.model}</b><span>{l.type} · {l.location} · {statusLabel(l.status)} · ends {fmtTime(l.endAt - tick)}</span></div><strong>{money(l.current)}</strong><select value={l.status || 'live'} onChange={e => action(`/api/admin/lot/${l.id}/status`, { status: e.target.value }, 'PATCH')}>{lotStatuses.map(s => <option key={s} value={s}>{statusLabel(s)}</option>)}</select><button className="secondary" onClick={() => setEditing(l)}><Pencil size={15}/> Edit</button><button className="danger" onClick={() => confirm(`Remove ${l.model}?`) && action(`/api/admin/lot/${l.id}`, {}, 'DELETE')}><Trash2 size={15}/></button></div>)}</div>{editing && <LotEditor lot={editing} close={() => setEditing(null)} save={async lot => { if (await action('/api/admin/lot', lot)) setEditing(null); }} />}</section>;
}
function blankLot() { return { id: '', brand: 'SHACMAN', model: '', type: 'Heavy Truck', location: 'Tbilisi Yard', year: 2022, hours: '0 km', increment: 1000, current: 10000, buyNow: 0, status: 'draft', endAt: Date.now() + 8 * 3600000, imageKey: 'shacman-x3000' }; }
function LotEditor({ lot, close, save }) {
  const [f, setF] = useState({ ...lot, endAt: toLocalInput(lot.endAt || Date.now() + 8 * 3600000) });
  const set = (k, v) => setF(x => ({ ...x, [k]: v }));
  return <div className="modalBackdrop" onMouseDown={close}><form className="lotEditor" onMouseDown={e => e.stopPropagation()} onSubmit={e => { e.preventDefault(); save(f); }}><button type="button" className="modalClose" onClick={close}><X size={18}/></button><span className="kicker"><Pencil size={15}/> Lot editor</span><h2>{lot.id ? 'Edit auction lot' : 'Add auction lot'}</h2><div className="editorGrid"><label>ID / slug<input value={f.id || ''} onChange={e => set('id', e.target.value)} placeholder="auto-from-model"/></label><label>Brand<input value={f.brand || ''} onChange={e => set('brand', e.target.value)} /></label><label>Model<input value={f.model || ''} onChange={e => set('model', e.target.value)} required /></label><label>Type<input value={f.type || ''} onChange={e => set('type', e.target.value)} /></label><label>Location<input value={f.location || ''} onChange={e => set('location', e.target.value)} /></label><label>Year<input type="number" value={f.year || ''} onChange={e => set('year', Number(e.target.value))} /></label><label>Km / hours<input value={f.hours || ''} onChange={e => set('hours', e.target.value)} /></label><label>Current bid<input type="number" value={f.current || 0} onChange={e => set('current', Number(e.target.value))} /></label><label>Increment<input type="number" value={f.increment || 0} onChange={e => set('increment', Number(e.target.value))} /></label><label>Buy Now<input type="number" value={f.buyNow || 0} onChange={e => set('buyNow', Number(e.target.value))} /></label><label>End time<input type="datetime-local" value={f.endAt || ''} onChange={e => set('endAt', e.target.value)} /></label><label>Status<select value={f.status || 'draft'} onChange={e => set('status', e.target.value)}>{lotStatuses.map(s => <option key={s} value={s}>{statusLabel(s)}</option>)}</select></label><label>Image<select value={f.imageKey || f.id || 'shacman-x3000'} onChange={e => set('imageKey', e.target.value)}>{Object.keys(images).map(k => <option key={k} value={k}>{k}</option>)}</select></label></div><div className="editorActions"><button type="button" className="secondary" onClick={close}>Cancel</button><button>Save lot</button></div></form></div>;
}
createRoot(document.getElementById('root')).render(<App />);
